import { createGlobalTheme } from "@vanilla-extract/css";

export const weight = createGlobalTheme(":root", {
  fontWeight: {
    regular: "400",
    medium: "500",
    semiBold: "600",
    bold: "700",
  },
});

export const vars = createGlobalTheme(":root", {
  screens: {
    sm: "550px",
    md: "768px",
    lg: "1280px",
    xl: "1920px",
  },
  colors: {
    white: "#FFFFFF",
    black: "#000000",
    blue900: "#0B3E91",
    blue800: "#0B69C8",
    blue700: "#0B7EE4",
    blue600: "#0A93FF",
    blue500: "#7DC6FF",
    blue400: "#B7DFFF",
    blue300: "#D4ECFF",
    blue200: "#E2F2FF",
    blue100: "#ECF6FF",
    blue50: "#F0F8FF",
    gray900: "#222729",
    gray800: "#353C3F",
    gray700: "#4A5256",
    gray600: "#5E696E",
    gray500: "#6E777C",
    gray400: "#AEB7BC",
    gray300: "#CFD6D9",
    gray200: "#E7EDF0",
    gray100: "#F1F4F6",
    gray50: "#F7F9FA",
    red900: "#792523",
    red800: "#9F3433",
    red700: "#C54343",
    red600: "#D64C4C",
    red500: "#DA5B5B",
    red400: "#DE6969",
    red300: "#E68686",
    red200: "#F2B2B2",
    red100: "#FAD8D8",
    red50: "#FFEFEF",
    yellow900: "#E4A400",
    yellow800: "#FBB500",
    yellow700: "#FDC100",
    yellow600: "#FFCC00",
    yellow500: "#FFD633",
    yellow400: "#FFE066",
    yellow300: "#FFE88D",
    yellow200: "#FFF0B3",
    yellow100: "#FFF4C6",
    yellow50: "#FFF7D9",
    green900: "#018827",
    green800: "#0A9A32",
    green700: "#10AC4C",
    green600: "#15BD66",
    green500: "#41CA80",
    green400: "#6CD69A",
    green300: "#97E2B4",
    green200: "#C2EECE",
    green100: "#D7F4DF",
    green50: "#EBFAEF",
  },
  typoType: {
    big: {
      fontSize: "6.4rem",
      lineHeight: "10rem",
      fontWeight: weight.fontWeight.bold,
    },
    d1: {
      fontSize: "4.8rem",
      lineHeight: "6.8rem",
      fontWeight: weight.fontWeight.bold,
    },
    d2: {
      fontSize: "4rem",
      lineHeight: "5.6rem",
      fontWeight: weight.fontWeight.bold,
    },
    d3: {
      fontSize: "3.6rem",
      lineHeight: "5rem",
      fontWeight: weight.fontWeight.bold,
    },
    d4: {
      fontSize: "3.2rem",
      lineHeight: "4.4rem",
      fontWeight: weight.fontWeight.bold,
    },
    d5: {
      fontSize: "2.8rem",
      lineHeight: "4rem",
      fontWeight: weight.fontWeight.bold,
    },
    d6: {
      fontSize: "2.4rem",
      lineHeight: "3.8rem",
      fontWeight: weight.fontWeight.bold,
    },
    h1: {
      fontSize: "2.6rem",
      lineHeight: "3.8rem",
      fontWeight: weight.fontWeight.medium,
    },
    h2: {
      fontSize: "2.4rem",
      lineHeight: "3.6rem",
      fontWeight: weight.fontWeight.medium,
    },
    h3: {
      fontSize: "2.2rem",
      lineHeight: "3.4rem",
      fontWeight: weight.fontWeight.medium,
    },
    h4: {
      fontSize: "2rem",
      lineHeight: "3rem",
      fontWeight: weight.fontWeight.medium,
    },
    h5: {
      fontSize: "1.9rem",
      lineHeight: "2.6rem",
      fontWeight: weight.fontWeight.medium,
    },
    h6: {
      fontSize: "1.7rem",
      lineHeight: "2.4rem",
      fontWeight: weight.fontWeight.medium,
    },
    h7: {
      fontSize: "1.6rem",
      lineHeight: "2.4rem",
      fontWeight: weight.fontWeight.medium,
    },
    h8: {
      fontSize: "1.5rem",
      lineHeight: "2rem",
      fontWeight: weight.fontWeight.medium,
    },
    h9: {
      fontSize: "1.4rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.medium,
    },
    h10: {
      fontSize: "1.3rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.medium,
    },
    h11: {
      fontSize: "1.1rem",
      lineHeight: "1.6rem",
      fontWeight: weight.fontWeight.medium,
    },
    b1: {
      fontSize: "2.6rem",
      lineHeight: "3.8rem",
      fontWeight: weight.fontWeight.regular,
    },
    b2: {
      fontSize: "2.4rem",
      lineHeight: "3.6rem",
      fontWeight: weight.fontWeight.regular,
    },
    b3: {
      fontSize: "2.2rem",
      lineHeight: "3.4rem",
      fontWeight: weight.fontWeight.regular,
    },
    b4: {
      fontSize: "2.0rem",
      lineHeight: "3rem",
      fontWeight: weight.fontWeight.regular,
    },
    b5: {
      fontSize: "1.9rem",
      lineHeight: "2.6rem",
      fontWeight: weight.fontWeight.regular,
    },
    b6: {
      fontSize: "1.7rem",
      lineHeight: "2.4rem",
      fontWeight: weight.fontWeight.regular,
    },
    b7: {
      fontSize: "1.6rem",
      lineHeight: "2.4rem",
      fontWeight: weight.fontWeight.regular,
    },
    b8: {
      fontSize: "1.5rem",
      lineHeight: "2rem",
      fontWeight: weight.fontWeight.regular,
    },
    b9: {
      fontSize: "1.4rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.regular,
    },
    b10: {
      fontSize: "1.3rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.regular,
    },
    b11: {
      fontSize: "1.1rem",
      lineHeight: "1.6rem",
      fontWeight: weight.fontWeight.regular,
    },
    button1: {
      fontSize: "1.9rem",
      lineHeight: "2.6rem",
      fontWeight: weight.fontWeight.medium,
    },
    button2: {
      fontSize: "1.7rem",
      lineHeight: "2.4rem",
      fontWeight: weight.fontWeight.medium,
    },
    button3: {
      fontSize: "1.5rem",
      lineHeight: "2rem",
      fontWeight: weight.fontWeight.medium,
    },
    button4: {
      fontSize: "1.3rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.medium,
    },
    button5: {
      fontSize: "1.1rem",
      lineHeight: "1.6rem",
      fontWeight: weight.fontWeight.medium,
    },
    l1: {
      fontSize: "1.6rem",
      lineHeight: "1.8rem",
      fontWeight: weight.fontWeight.medium,
    },
    l2: {
      fontSize: "1.4rem",
      lineHeight: "1.4rem",
      fontWeight: weight.fontWeight.medium,
    },
    l3: {
      fontSize: "1.2rem",
      lineHeight: "1.2rem",
      fontWeight: weight.fontWeight.medium,
    },
    l4: {
      fontSize: "1rem",
      lineHeight: "1rem",
      fontWeight: weight.fontWeight.medium,
    },
    p: {
      fontSize: "1.7rem",
      lineHeight: "3rem",
      fontWeight: weight.fontWeight.regular,
    },
    p3: {
      fontSize: "1.4rem",
      lineHeight: "2.2rem",
      fontWeight: weight.fontWeight.regular,
    },
  },
  space: {
    4: "0.4rem",
    6: "0.6rem",
    8: "0.8rem",
    12: "1.2rem",
    16: "1.6rem",
    24: "2.4rem",
    32: "3.2rem",
    72: "7.2rem",
  },
});

export type ThemeColors = keyof (typeof vars)["colors"];
